name: rootcynaps
channels:
  - openalea3
  - conda-forge
dependencies:
  - python
  - scipy
  - numpy
  - openalea.mtg
  # metafspm
  - pyyaml
  # fspm-utility
  - pandas
  - salib
  - xarray
  - pyvista
  - matplotlib
  - pint
  - trimesh
  - openalea.plantgl